In [1]:
import pandas as pd

# 1. Call datasets, remove duplicates, NaN.

In [2]:
# Call the clinical dataset and remove duplicates
clinical = pd.read_csv('../Clinical_dataset/clinical_modi_1.csv', sep='\t')

In [3]:
# column name change: age_at_index -> age
clinical.rename(columns={'age_at_index':'age'}, inplace=True)
clinical.drop_duplicates(subset='case_submitter_id', inplace=True)

In [4]:
# Check missing values in AGE, GENDER, STAGE and remove row with missing.
print('Count of Gender information not available cases:\n', clinical['gender'].isnull().sum(axis=0))
print('\n')
print('Count of STAGE information not available cases:\n', clinical['Stage'].value_counts(dropna=False))
print('\n')
print('Count of AGE information not available cases:\n', clinical['age'].isnull().sum(axis=0))

Count of Gender information not available cases:
 63


Count of STAGE information not available cases:
 1.0    279
2.0    124
3.0     85
NaN     71
4.0     26
Name: Stage, dtype: int64


Count of AGE information not available cases:
 82

In [5]:
# Remove NaN containing row in 'AGE' & 'STAGE'
clinical = clinical.dropna(subset=['age', 'Stage'], axis=0)
clinical

,case_id,case_submitter_id,project_id,age,age_is_obfuscated,cause_of_death,cause_of_death_source,country_of_residence_at_enrollment,days_to_birth,days_to_death,...,treatment_arm,treatment_dose,treatment_dose_units,treatment_effect,treatment_effect_indicator,treatment_frequency,treatment_intent_type,treatment_or_therapy,treatment_outcome,treatment_type
0,0075437e-ba1a-46be-86d6-9773209a2b5e,TCGA-62-A471,TCGA-LUAD,64.0,NaN,NaN,NaN,NaN,-23689.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,"Pharmaceutical Therapy, NOS"
2,009be09b-f9f6-43b7-8f45-4a648f8123ce,TCGA-67-3773,TCGA-LUAD,84.0,NaN,NaN,NaN,NaN,-30706.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not reported,NaN,"Radiation Therapy, NOS"
5,01e9888d-b5b9-48f1-8ba6-8a89af108a04,TCGA-NJ-A7XG,TCGA-LUAD,49.0,NaN,NaN,NaN,NaN,-18127.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no,NaN,"Radiation Therapy, NOS"
7,0232d299-4cdf-4fd7-9a5e-8d13c208b40c,TCGA-91-6848,TCGA-LUAD,59.0,NaN,NaN,NaN,NaN,-21829.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,"Pharmaceutical Therapy, NOS"
9,028e99e9-5b9a-4954-bb6e-6d4709a3cea8,TCGA-55-6986,TCGA-LUAD,74.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no,NaN,"Radiation Therapy, NOS"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1097,fe3eeeb6-0db4-46d7-a020-55604d474c12,TCGA-78-7167,TCGA-LUAD,77.0,NaN,NaN,NaN,NaN,-28295.0,2681.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no,NaN,"Radiation Therapy, NOS"
1099,fe714ac0-f874-426a-924b-a2980232b5f7,TCGA-55-8616,TCGA-LUAD,58.0,NaN,NaN,NaN,NaN,-21225.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not reported,NaN,"Radiation Therapy, NOS"
1101,ff07ea4b-4e50-410d-99d6-96a351dad7b1,TCGA-55-7570,TCGA-LUAD,60.0,NaN,NaN,NaN,NaN,-22218.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no,NaN,"Radiation Therapy, NOS"
1103,ff9def3d-17e5-4ef6-b74e-933f11ed6f00,TCGA-78-7146,TCGA-LUAD,71.0,NaN,NaN,NaN,NaN,-26272.0,173.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no,NaN,"Radiation Therapy, NOS"
1105,ffb0c0b7-165e-4439-b3e6-62431f40b7fe,TCGA-44-3398,TCGA-LUAD,77.0,NaN,NaN,NaN,NaN,-28392.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no,NaN,"Pharmaceutical Therapy, NOS"

In [6]:
# Call Exposuer dataset and remove duplecates.
exposure = pd.read_csv('../Clinical_dataset/exposure_modi_1.csv', sep='\t')
exposure.drop_duplicates(subset='case_submitter_id',inplace=True)
exposure.head()

,case_id,case_submitter_id,project_id,age_at_onset,alcohol_days_per_week,alcohol_drinks_per_day,alcohol_history,alcohol_intensity,alcohol_type,asbestos_exposure,...,smoking_frequency,time_between_waking_and_first_smoke,tobacco_smoking_onset_year,tobacco_smoking_quit_year,tobacco_smoking_status,tobacco_use_per_day,type_of_smoke_exposure,type_of_tobacco_used,weight,years_smoked
0,0075437e-ba1a-46be-86d6-9773209a2b5e,TCGA-62-A471,TCGA-LUAD,NaN,NaN,NaN,Not Reported,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,009be09b-f9f6-43b7-8f45-4a648f8123ce,TCGA-67-3773,TCGA-LUAD,NaN,NaN,NaN,Not Reported,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01e9888d-b5b9-48f1-8ba6-8a89af108a04,TCGA-NJ-A7XG,TCGA-LUAD,NaN,NaN,NaN,Not Reported,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0232d299-4cdf-4fd7-9a5e-8d13c208b40c,TCGA-91-6848,TCGA-LUAD,NaN,NaN,NaN,Not Reported,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,028e99e9-5b9a-4954-bb6e-6d4709a3cea8,TCGA-55-6986,TCGA-LUAD,NaN,NaN,NaN,Not Reported,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Check missing values in PY and remove row with missing.
print('# of PY information not available cases:', exposure['pack_years_smoked'].isnull().sum(axis=0))
exposure = exposure.dropna(subset=['pack_years_smoked'], axis=0)
exposure.head()

# of PY information not available cases: 166

,case_id,case_submitter_id,project_id,age_at_onset,alcohol_days_per_week,alcohol_drinks_per_day,alcohol_history,alcohol_intensity,alcohol_type,asbestos_exposure,...,smoking_frequency,time_between_waking_and_first_smoke,tobacco_smoking_onset_year,tobacco_smoking_quit_year,tobacco_smoking_status,tobacco_use_per_day,type_of_smoke_exposure,type_of_tobacco_used,weight,years_smoked
0,0075437e-ba1a-46be-86d6-9773209a2b5e,TCGA-62-A471,TCGA-LUAD,NaN,NaN,NaN,Not Reported,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,035c0b2b-c722-443b-8962-db4ee92c7532,TCGA-86-6851,TCGA-LUAD,NaN,NaN,NaN,Not Reported,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,03d09c05-49ab-4ba6-a8d7-e7ccf71fafd2,TCGA-05-4245,TCGA-LUAD,NaN,NaN,NaN,Not Reported,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,06fe7f3e-4edd-4150-981c-93787ea19b39,TCGA-55-8615,TCGA-LUAD,NaN,NaN,NaN,Not Reported,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,079ae0b3-b64b-4b8e-ab7d-225b8046568c,TCGA-86-7954,TCGA-LUAD,NaN,NaN,NaN,Not Reported,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0

In [8]:
# Call CCL2 expression dataset (lower 2/3 vs. rest higher)
TREM2_LUAD_L67_H33 = pd.read_csv('./Expression/TREM2_LUAD_L67_H33.csv')

# 2. Merge organized datasets and select only necessary columns.

In [9]:
# Sereial merging on 'case_submitter_id'
df_1 = pd.merge(clinical, exposure, on='case_submitter_id')
df_2 = pd.merge(df_1, TREM2_LUAD_L67_H33, left_on='case_submitter_id', right_on='Patient', how='left')

In [10]:
# Select only required columns
# 1st check the column names
cols = list(df_2.columns.values.tolist())
cols

['case_id_x',
 'case_submitter_id',
 'project_id_x',
 'age',
 'age_is_obfuscated',
 'cause_of_death',
 'cause_of_death_source',
 'country_of_residence_at_enrollment',
 'days_to_birth',
 'days_to_death',
 'ethnicity',
 'gender',
 'occupation_duration_years',
 'premature_at_birth',
 'race',
 'vital_status',
 'weeks_gestation_at_birth',
 'year_of_birth',
 'year_of_death',
 'adrenal_hormone',
 'age_at_diagnosis',
 'ajcc_clinical_m',
 'ajcc_clinical_n',
 'ajcc_clinical_stage',
 'ajcc_clinical_t',
 'ajcc_pathologic_m',
 'ajcc_pathologic_n',
 'ajcc_pathologic_stage',
 'Stage',
 'ajcc_pathologic_t',
 'ajcc_staging_system_edition',
 'anaplasia_present',
 'anaplasia_present_type',
 'ann_arbor_b_symptoms',
 'ann_arbor_b_symptoms_described',
 'ann_arbor_clinical_stage',
 'ann_arbor_extranodal_involvement',
 'ann_arbor_pathologic_stage',
 'best_overall_response',
 'breslow_thickness',
 'burkitt_lymphoma_clinical_variant',
 'child_pugh_classification',
 'circumferential_resection_margin',
 'classification_of_tumor',
 'cog_liver_stage',
 'cog_neuroblastoma_risk_group',
 'cog_renal_stage',
 'cog_rhabdomyosarcoma_risk_group',
 'days_to_best_overall_response',
 'days_to_diagnosis',
 'days_to_last_follow_up',
 'days_to_last_known_disease_status',
 'days_to_recurrence',
 'eln_risk_classification',
 'enneking_msts_grade',
 'enneking_msts_metastasis',
 'enneking_msts_stage',
 'enneking_msts_tumor_site',
 'esophageal_columnar_dysplasia_degree',
 'esophageal_columnar_metaplasia_present',
 'figo_stage',
 'figo_staging_edition_year',
 'first_symptom_prior_to_diagnosis',
 'gastric_esophageal_junction_involvement',
 'gleason_grade_group',
 'gleason_grade_tertiary',
 'gleason_patterns_percent',
 'goblet_cells_columnar_mucosa_present',
 'greatest_tumor_dimension',
 'gross_tumor_weight',
 'icd_10_code',
 'igcccg_stage',
 'inpc_grade',
 'inpc_histologic_group',
 'inrg_stage',
 'inss_stage',
 'international_prognostic_index',
 'irs_group',
 'irs_stage',
 'ishak_fibrosis_score',
 'iss_stage',
 'largest_extrapelvic_peritoneal_focus',
 'last_known_disease_status',
 'laterality',
 'lymph_node_involved_site',
 'lymph_nodes_positive',
 'lymph_nodes_tested',
 'lymphatic_invasion_present',
 'margin_distance',
 'margins_involved_site',
 'masaoka_stage',
 'medulloblastoma_molecular_classification',
 'metastasis_at_diagnosis',
 'metastasis_at_diagnosis_site',
 'method_of_diagnosis',
 'micropapillary_features',
 'mitosis_karyorrhexis_index',
 'mitotic_count',
 'morphology',
 'non_nodal_regional_disease',
 'non_nodal_tumor_deposits',
 'ovarian_specimen_status',
 'ovarian_surface_involvement',
 'papillary_renal_cell_type',
 'percent_tumor_invasion',
 'perineural_invasion_present',
 'peripancreatic_lymph_nodes_positive',
 'peripancreatic_lymph_nodes_tested',
 'peritoneal_fluid_cytological_status',
 'pregnant_at_diagnosis',
 'primary_diagnosis',
 'primary_disease',
 'primary_gleason_grade',
 'prior_malignancy',
 'prior_treatment',
 'progression_or_recurrence',
 'residual_disease',
 'satellite_nodule_present',
 'secondary_gleason_grade',
 'site_of_resection_or_biopsy',
 'sites_of_involvement',
 'supratentorial_localization',
 'synchronous_malignancy',
 'tissue_or_organ_of_origin',
 'transglottic_extension',
 'tumor_confined_to_organ_of_origin',
 'tumor_depth',
 'tumor_focality',
 'tumor_grade',
 'tumor_largest_dimension_diameter',
 'tumor_regression_grade',
 'tumor_stage',
 'vascular_invasion_present',
 'vascular_invasion_type',
 'weiss_assessment_score',
 'who_cns_grade',
 'who_nte_grade',
 'wilms_tumor_histologic_subtype',
 'year_of_diagnosis',
 'chemo_concurrent_to_radiation',
 'days_to_treatment_end',
 'days_to_treatment_start',
 'initial_disease_status',
 'number_of_cycles',
 'reason_treatment_ended',
 'regimen_or_line_of_therapy',
 'route_of_administration',
 'therapeutic_agents',
 'treatment_anatomic_site',
 'treatment_arm',
 'treatment_dose',
 'treatment_dose_units',
 'treatment_effect',
 'treatment_effect_indicator',
 'treatment_frequency',
 'treatment_intent_type',
 'treatment_or_therapy',
 'treatment_outcome',
 'treatment_type',
 'case_id_y',
 'project_id_y',
 'age_at_onset',
 'alcohol_days_per_week',
 'alcohol_drinks_per_day',
 'alcohol_history',
 'alcohol_intensity',
 'alcohol_type',
 'asbestos_exposure',
 'bmi',
 'cigarettes_per_day',
 'coal_dust_exposure',
 'environmental_tobacco_smoke_exposure',
 'exposure_duration',
 'exposure_duration_years',
 'exposure_type',
 'height',
 'marijuana_use_per_week',
 'pack_years_smoked',
 'parent_with_radiation_exposure',
 'radon_exposure',
 'respirable_crystalline_silica_exposure',
 'secondhand_smoke_as_child',
 'smokeless_tobacco_quit_age',
 'smoking_frequency',
 'time_between_waking_and_first_smoke',
 'tobacco_smoking_onset_year',
 'tobacco_smoking_quit_year',
 'tobacco_smoking_status',
 'tobacco_use_per_day',
 'type_of_smoke_exposure',
 'type_of_tobacco_used',
 'weight',
 'years_smoked',
 'Patient',
 'Days',
 'Status',
 'Expression',
 'Group']

In [11]:
# then select only necessary columns
df_3 = df_2[['case_submitter_id', 'Patient', 'Status','days_to_death', 'days_to_last_follow_up','Expression', 'Group', 'age', 'gender', 'Stage', 'pack_years_smoked']]
df_3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 341 entries, 0 to 340
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   case_submitter_id       341 non-null    object
 1   Patient                 331 non-null    object
 2   Status                  331 non-null    object
 3   days_to_death           119 non-null    float64
 4   days_to_last_follow_up  262 non-null    float64
 5   Expression              331 non-null    float64
 6   Group                   331 non-null    object
 7   age                     341 non-null    float64
 8   gender                  341 non-null    object
 9   Stage                   341 non-null    float64
 10  pack_years_smoked       341 non-null    float64
dtypes: float64(6), object(5)
memory usage: 32.0+ KB

# 3. Change matching variable to numeric form

In [12]:
# change expression to numeric form: THIS PART IS IMPORTANT BECAUSE THIS SETS WHICH IS EXPERIMENT GROUP and WHICH is CONTROL.
print(df_3['Group'].value_counts(dropna=False))

df_3.loc[(df_3.Group == 'Low'), 'Group']=0
df_3.loc[(df_3.Group == 'High'), 'Group']=1

Low     229
High    102
NaN      10
Name: Group, dtype: int64

/home/yschang/.local/lib/python3.8/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [13]:
# change survival stuatus to numeric form. 
print(df_3['Status'].value_counts(dropna=False))

df_3.loc[(df_3.Status !='Dead'), 'Status']=0
df_3.loc[(df_3.Status == 'Dead'), 'Status']=1

Alive    214
Dead     117
NaN       10
Name: Status, dtype: int64

In [14]:
# change gender to numeric form.
print(df_3['gender'].value_counts(dropna=False))
df_3.loc[df_3['gender'] == 'male', 'gender'] = 1
df_3.loc[df_3['gender'] == 'female', 'gender'] = 2

female    177
male      164
Name: gender, dtype: int64

In [15]:
print(df_3['Status'].value_counts(dropna=False))
print('\n')
print(df_3['Group'].value_counts(dropna=False))
print('\n')
print(df_3['gender'].value_counts(dropna=False))

0    224
1    117
Name: Status, dtype: int64


0.0    229
1.0    102
NaN     10
Name: Group, dtype: int64


2    177
1    164
Name: gender, dtype: int64

In [16]:
df_3.isnull().sum()

case_submitter_id           0
Patient                    10
Status                      0
days_to_death             222
days_to_last_follow_up     79
Expression                 10
Group                      10
age                         0
gender                      0
Stage                       0
pack_years_smoked           0
dtype: int64

In [17]:
# Remove NaN containing row in 'AGE' & 'STAGE'
df_4 = df_3.dropna(subset=['Group', 'Expression','age', 'gender', 'Stage', 'pack_years_smoked'], axis=0)
df_4.isnull().sum()

case_submitter_id           0
Patient                     0
Status                      0
days_to_death             213
days_to_last_follow_up     78
Expression                  0
Group                       0
age                         0
gender                      0
Stage                       0
pack_years_smoked           0
dtype: int64

# 4. Save for further analysis

In [18]:
df_4.to_csv('./Results/Merged_TCGA_LUAD_TREM2_L67_H33.csv')